apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-app
  labels:
    app: gcp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-app
  template:
    metadata:
      labels:
        app: gcp-app
    spec:
      containers:
      - name: gcp-app
        image: gcr.io/<PROJECT-ID>/gcp-app:latest
        ports:
        - containerPort: 8080